drop table if exists users_items cascade;
drop table if exists requests cascade;
drop table if exists items cascade;
drop table if exists bookings cascade;
drop table if exists comments cascade;

CREATE TABLE IF NOT EXISTS users_items
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR NOT NULL,
    requestor_id INTEGER REFERENCES users_items (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    description  VARCHAR NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id     INTEGER REFERENCES users_items (id),
    request_id   INTEGER REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    INTEGER REFERENCES items (id),
    booker_id  INTEGER REFERENCES users_items (id),
    status     VARCHAR                     NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR                     NOT NULL,
    item_id   INTEGER REFERENCES items (id),
    author_id INTEGER REFERENCES users_items (id),
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);